export const toolStatusLabels: Record<string, string> = {
  manage_artifact: 'Working on artifact',
  delete_artifact: 'Preparing to delete artifact',
  open_artifact: 'Opening artifact',
  manage_project_context: 'Updating project context',
  search_gmail: 'Searching your email',
  draft_email: 'Drafting an email',
  manage_project: 'Managing project',
  manage_bookmarks: 'Saving a bookmark',
  manage_dashboard: 'Updating dashboard',
  manage_notification_rules: 'Setting up alert rule',
  manage_preferences: 'Updating preferences',
  manage_training: 'Running training',
  manage_notepad: 'Updating notepad',
  manage_contacts: 'Updating contacts',
  search_web: 'Searching the web',
  manage_action_items: 'Managing action items',
  spawn_background_job: 'Starting background research',
  create_watch: 'Setting up watch',
  list_watches: 'Checking watches',
  cancel_watch: 'Canceling watch',
  ask_structured_question: 'Asking question',
  quick_confirm: 'Asking for confirmation',
  query_sales: 'Checking sales data',
  search_texts: 'Searching texts',
  manage_text_contacts: 'Updating text contacts',
  manage_group_whitelist: 'Managing group whitelist',
  search_conversation_history: 'Searching past conversations',
  request_additional_context: 'Loading additional context',
  get_activity_log: 'Checking activity log',
}
