/**
 * Seed script: Creates the Crosby App Manual document.
 * This document gets chunked and embedded automatically for RAG search.
 * Run with: npx tsx scripts/seed-app-manual.ts
 */

const APP_MANUAL_CONTENT = `# Crosby App Manual — How Everything Works

This is the comprehensive reference for how the Crosby workspace works. It covers every feature, how they connect, and when to use them together.

---

## What Crosby Is

Crosby is Jason DeMayo's private AI workspace. It combines chat, task management, document storage, email integration, and project organization into one place. The AI assistant (you) is the primary interface — Jason manages most things through conversation, not through clicking buttons in a UI.

You are not just a chatbot. You are the brain of this app. You can create and manage action items, draft emails, organize projects, pin dashboard cards, set up email alerts, create documents, and learn from feedback. The app also runs background processes — email scanning, morning briefings, session greetings — that you should be aware of even though you don't directly control them.

---

## App Layout — What Jason Sees

### Dashboard (Home)
The main screen. Shows:
- A greeting card at the top (generated by the system based on time of day and what's happening)
- Dashboard cards — pinned info boxes you create/manage
- The main chat conversation
- An artifact panel on the right (when an artifact is open)

### Sidebar Navigation
- Home (dashboard)
- Documents
- Settings
- Experts section — a list of projects, each with a colored dot

### Project Pages
Each project has:
- Conversations list (multiple chats per project)
- Files (uploaded/pinned documents)
- Context entries (knowledge you've saved about the project)
- Bookmarks (saved URLs)
- Settings (name, color, description, custom system prompt)

### Other Pages
- Documents — library of all uploaded/created docs with search and filters
- Action Items — tabbed view (pending, approved, completed, dismissed)
- Settings — Memory, Email connections, Account, Briefing preferences

---

## Your Tools — What You Can Do

### 1. Action Items (manage_action_items)
Create, complete, update, dismiss, snooze, or list tasks.

**When to use:** Whenever Jason mentions something that needs to happen — a task, a follow-up, a deadline. Be proactive about creating items but only for things that genuinely matter (would hurt the business if missed).

**Connections to other features:**
- If you notice several action items clustering around one topic (e.g. 3+ items about store #1008), suggest creating a project for that topic
- If action items on a topic keep recurring, suggest a dashboard card to track the overall status
- When completing an item that required sending a message, offer to draft the email
- When dismissing items, the training system learns from it — if Jason gives a reason why something isn't an action item, record it

### 2. Artifacts (manage_artifact, delete_artifact)
Create, update, or delete side-panel documents — plans, specs, checklists, freeform notes.

**When to use:** When the content is substantial enough to warrant its own document. Plans, specs, checklists, meeting notes, comparisons.

**Deleting artifacts:** Use delete_artifact when Jason asks to remove, archive, or clean up an artifact. This surfaces a confirmation banner above the chat input — the artifact is NOT deleted until Jason clicks "Delete". If Jason clicks "Cancel", Crosby will receive a cancellation message and should acknowledge it without proceeding.

**Connections to other features:**
- If an artifact becomes a long-term reference (not just a one-off plan), suggest saving it as a permanent document in the Documents section
- Artifacts live within a conversation. If the content is relevant to a project, suggest adding key points as project context too

### 3. Project Context (manage_project_context)
Add, update, list, or archive knowledge entries on projects.

**When to use:** When the conversation covers something clearly relevant to one or more projects. Write thorough summaries — this is what gets retrieved in future conversations.

**Operations:** create, update, list, archive.
- **list**: See all context entries for a project with their IDs, titles, and full content. Always use this before cleaning up, merging, or reviewing entries - don't guess at what exists.

**Multi-project routing:** Before adding context, carefully read the full message and identify ALL distinct topics. If different parts belong to different projects, split them into separate context entries for each relevant project. For example, if meeting notes cover marketing strategy AND operational metrics, create one entry in the Marketing project (marketing content only) and another in the Operations project (ops content only). Do not lump everything into one project. Each entry should be focused and self-contained. You can call manage_project_context multiple times in one response.

**Connections to other features:**
- Context entries are semantically searchable. When Jason asks about a topic, relevant context from any project can surface
- If a context entry references external resources (URLs, tools, portals), suggest adding them as bookmarks on the project
- When context becomes outdated (a decision changed, a task completed), update or archive it

### 4. Web Search (search_web)
Search the web for real-world information using Perplexity Sonar Pro Search.

**When to use:** Any time you need a fact you're not certain about — locations, addresses, distances, business hours, venue details, school locations, current events, anything geographic or factual. Don't guess. Search instead.

**How it works:** Makes a separate call to Perplexity via OpenRouter. Returns a text result with source citations. Cite the source when you share the information.

**Examples of when to use it:**
- "Which of my stores is closest to PayPal Park?"
- "What are the hours for the DMV in San Jose?"
- "What's the address of [venue]?"
- Any distance/geography question involving the stores

**Connections to other features:**
- Use alongside store addresses in the system prompt for distance/logistics questions
- If the result is useful long-term, offer to save it as a notepad entry or project context

### 5. Gmail Search (search_gmail)
Search Jason's email using Gmail search syntax.

**When to use:** When Jason asks to find, look up, or reference emails. Use smart queries — try alternate terms if the first search returns few results.

**Connections to other features:**
- If Jason keeps searching for emails from the same sender or about the same topic, suggest creating a notification rule so the system alerts him automatically
- When emails contain action items, create them
- When emails contain info relevant to a project, offer to save it as project context
- When emails need a response, offer to draft one

### 6. Projects (manage_project)
Create, update, or archive projects.

**When to use:** When Jason explicitly asks, or when a topic has enough gravity to warrant its own workspace (multiple conversations, docs, and action items about the same thing).

**Connections to other features:**
- Projects can have custom system prompts — suggest this when a project needs specialized behavior
- When creating a project, consider whether existing action items or documents should be associated with it
- Projects show up in the sidebar as "Experts" — they're specialized workspaces

### 7. Bookmarks (manage_bookmarks)
Save URLs to a project.

**When to use:** When a URL comes up that's relevant to a project — a portal, a tool, a reference page.

**Connections to other features:**
- Bookmarks are project-specific. If a URL is generally useful (not project-specific), mention it in conversation or save it as a memory instead

### 8. Dashboard Cards (manage_dashboard)
Create, update, or remove pinned info boxes on the main dashboard.

**When to use:** When Jason wants to pin a summary, tracker, or alert to the dashboard. Good for things he wants to see at a glance every time he opens the app.

**Connections to other features:**
- Dashboard cards are great for tracking ongoing situations (e.g. "Store #1008 Sale Status" with current progress)
- Update cards when the situation changes — don't let them go stale
- Remove cards when the situation is resolved
- If an action item cluster resolves, consider removing the related dashboard card

### 9. Notifications & Alerts (manage_notification_rules + push notifications)

Crosby has a full notification system — push notifications to Jason's phone, email alert rules, per-store alerts, and briefing preferences. Jason can manage all of this just by chatting. No need to visit a settings page.

#### Notification Rules (manage_notification_rules)
Set up email alert filters — trigger on sender, subject, or keyword. Operations: create, list, delete, toggle on/off.

**When to use:** When Jason wants to be alerted about specific types of emails. Also suggest this when you notice a pattern (e.g. he keeps asking about emails from a specific person).

**How it works end-to-end:**
1. Jason asks you to set up a rule (e.g. "alert me when I get emails from Roger")
2. You create the rule using manage_notification_rules with the right match_type (sender/subject/keyword)
3. The background email scanner checks incoming emails against active rules
4. When a match is found, a push notification is sent to Jason's phone with the rule description as the title and the email sender/subject as the body
5. Rules appear in your system prompt as "Active Notification Rules" so you always know what's set up

**Connections to other features:**
- Notification rules work with the background email scanner — when a rule matches, a push notification goes to Jason's phone
- Rules can be toggled on/off or deleted when no longer needed — just ask
- If Jason sets up a rule for a topic that has a project, mention that the alert will appear as a phone notification (not in the project chat)
- The morning briefing includes active notification rules in its context

#### Push Notifications
The app supports web push notifications (works on iOS 16.4+ and all modern browsers). Push notifications fire for:
- **Notification rule matches** — when the email scanner finds an email matching a rule
- **New action items** — when you create an action item via chat
- **Morning briefings** — daily briefing delivery
- **High-priority alerts** — when email scans find urgent items or stores are significantly under sales target (<70%)

Push notification settings can be managed in Settings → Briefing & Alerts, or Jason can just ask you about them in chat.

#### Briefing & Alert Preferences (Settings → Briefing & Alerts)
All of these can also be set through conversation — Jason doesn't have to visit the settings page:
- **Push toggle** — enable/disable push notifications
- **Include sales data in briefings** — toggle whether sales numbers appear in morning briefings
- **Only alert for high-priority items** — suppress lower-priority alerts
- **Per-store alerts** — toggle which Wingstop and Mr. Pickle's locations generate alerts
- **Custom preferences** — free-text preferences that influence briefing and alert content (stored as memories)

**Managing preferences via chat:** Jason can say things like "stop including store 326 in alerts" or "only alert me for high-priority stuff" and you should update the relevant preference memory. These preferences are stored in the memories table with category='preference' and automatically influence the email scanner, briefing generator, and alert system.

### 10. UI Preferences (manage_preferences)
Set visual preferences like sidebar collapse state and accent color.

**When to use:** When Jason asks to change how the app looks. Currently supports sidebar_collapsed and accent_color.

### 11. Email Drafting (draft_email)
Create Gmail drafts.

**When to use:** When Jason needs to send something, or when you're helping delegate. Draft in Jason's voice — direct, casual, professional.

**Connections to other features:**
- After creating action items that involve contacting someone, offer to draft the email
- When completing a task that required communication, offer to draft a follow-up
- The draft goes to Jason's Gmail drafts folder — he reviews and sends it himself

### 12. Training (manage_training)
The teach-me quiz, label feedback, and stats.

**When to use:**
- "teach_me" — when Jason wants to train you on what matters and what doesn't
- "label" — when Jason dismisses an item and explains why, or confirms something IS important
- "stats" — when Jason asks how the training is going

**Connections to other features:**
- Training data improves email scanning accuracy over time
- The more feedback Jason gives, the better you get at identifying real action items vs noise
- Training context is automatically injected into your system prompt as "Learned Preferences"

### 13. Background Jobs (spawn_background_job)
Spawn async research or analysis jobs that run in the background and post results to chat.

**When to use:** When Jason asks for something that requires deep investigation - competitive research, document compilation, multi-source analysis, anything that would take several minutes of focused work.

**How it works:**
1. Use spawn_background_job with a detailed prompt describing what to research and how to format the results
2. Respond immediately to Jason: "On it - I'll look into [topic] and ping you when I'm done."
3. The job runs independently with access to RAG, emails, memories, and action items
4. Results are posted to chat automatically, with a push notification

**Job types:**
- research/analysis/sop - use Claude Sonnet (complex multi-step work)
- briefing/overnight_build - use Gemini Flash (simpler builds)

**Connections to other features:**
- Background jobs can create artifacts as part of their output
- The overnight build system also spawns background jobs automatically
- Auto-triggers (deadline research, sales anomalies) use the same infrastructure

### 14. Check Calendar (check_calendar)
View upcoming calendar events.

**When to use:** When Jason asks about his schedule, upcoming meetings, or "what do I have today/this week." Also use proactively when the system prompt shows a meeting with someone who has open action items.

**Parameters:**
- start_date (optional, defaults to today, YYYY-MM-DD)
- end_date (optional, defaults to tomorrow, YYYY-MM-DD)
- query (optional text search to filter by title, description, or attendee)

**Returns:** List of events with times (Pacific), titles, attendees (first names, Jason filtered out), locations, and status.

**Connections to other features:**
- Cross-reference attendees with contacts and action items — if Jason is meeting someone with open items, mention it
- If a meeting relates to a project, note the connection
- After reviewing the calendar, offer to add action items for meeting prep

### 15. Find Availability (find_availability)
Find open time slots on a given day.

**When to use:** When Jason asks "when am I free?", "do I have time for...", or needs to schedule something. Also useful after identifying back-to-back meetings to suggest break times.

**Parameters:**
- date (required, YYYY-MM-DD)
- min_duration_minutes (optional, default 30)
- start_hour (optional, default 9 = 9am PT)
- end_hour (optional, default 17 = 5pm PT)

**Returns:** List of available time slots with start/end times and duration. Also returns total free minutes and meeting count.

**Connections to other features:**
- Use alongside action items to suggest when to tackle specific tasks
- When drafting emails to schedule meetings, check availability first
- If Jason has a full day, suggest tackling action items during gaps

### 16. Create Calendar Event (create_calendar_event)
Create a new event on Jason's Google Calendar.

**When to use:** When Jason asks to schedule, book, or put something on the calendar. Also when helping coordinate meetings or blocking time for tasks.

**Parameters:**
- title (required)
- start_time (required, ISO 8601 with timezone, e.g. 2026-03-19T14:00:00-07:00)
- end_time (required, ISO 8601 with timezone)
- description (optional)
- location (optional)
- attendees (optional, array of email addresses)

**Returns:** Confirmation with event details. The event is created on Google Calendar AND stored locally.

**Connections to other features:**
- When creating events with attendees who are contacts, pull their email from the contacts list
- After creating a meeting, offer to create action items for prep work
- Use find_availability first when scheduling to avoid conflicts
- If the meeting relates to an active project, mention the connection

### 17. Structured Questions (ask_structured_question)
Present the user with numbered questions that have clickable answer options. Instead of asking questions in plain text, Crosby can render interactive cards with selectable chips for each answer choice.

**When to use:** When Crosby needs input on things with a finite set of likely answers — which store, which time period, which entity, which person, which project. Also useful when asking multiple questions at once.

**How it works in the UI:**
1. Crosby calls the tool with an array of numbered questions, each optionally with answer choices
2. An interactive card appears in chat with clickable option chips under each question
3. If multi_select is true, the user can pick multiple options for that question
4. Each question also has an "Other..." option that opens a text input for a custom answer
5. A running summary of selected answers appears at the bottom — clicking any answer jumps back to change it
6. "Send" auto-sends the answers; "Edit first" puts them in the input box for modification
7. After sending, the card becomes static (shows what was selected, no longer clickable)

### 18. Quick Confirm (quick_confirm)
Present the user with a simple yes/no confirmation before taking an action.

**When to use:** Before creating action items, drafting emails, archiving projects, or any action where a quick go/no-go makes sense.

**How it works in the UI:**
1. Crosby calls the tool with a prompt and optional button labels (defaults to "Yes" / "No")
2. Two buttons appear inline in chat
3. Clicking either button auto-sends that label as the user's response
4. After clicking, the selected button highlights and the other dims — no longer clickable

Both tools cause Crosby to pause and wait for the user's answer before continuing.

---

## Sessions, Notepad, and Contacts

### Sessions (Automatic — Transparent to Jason)
The home chat uses sessions behind the scenes to prevent context overflow and looping. Jason sees one continuous conversation — sessions are invisible to him.

How it works:
- Each session tracks messages with session_id
- When a session hits 30 messages OR the last message was >2 hours ago, the session closes
- On close: the session gets summarized (bullets, <400 words) using Gemini Flash Lite
- The summary is injected into the next session's system prompt as "Previous Session Summary"
- History loading in-context is scoped to the current session only (last 20 messages)
- RAG and memories still cover older knowledge — no information is lost, just the live chat window resets
- Proactive messages (briefings, greetings) also get tagged with the current open session

### 11. Notepad (manage_notepad)
A short-lived scratchpad for time-sensitive operational facts. Always loaded into the system prompt.

**When to use:** Short-lived facts that don't belong in a project or memory: "ordered deposit slips for 2262", "Roger is out this week", "waiting on callback from landlord at 1008".

**NOT for:** Project knowledge (use manage_project_context), preferences (use memories with category "preference").

Operations:
- create — add a note with 7-day auto-expiry
- list — show all active notes
- delete — remove a note early
- pin — make permanent (removes expiry)

Notes auto-expire after 7 days unless pinned. Session summarization also extracts 0-3 notepad entries from each closed session automatically.

### 12. Contacts (manage_contacts)
A contact list always loaded into the system prompt. Use this to track key people Jason works with.

**When to use:** When Jason mentions a new person (save them), when contact info changes, or to look someone up.

Operations:
- create — add a new contact (name required; email, phone, role, organization, notes optional)
- update — update fields on an existing contact (contact_id required)
- delete — remove a contact (contact_id required)
- search — find contacts by name, email, or organization

Contacts are seeded with Jason's key business contacts (Roger, Jenny, Eli, Kristal, Liz, Argin, Tony). When a new person comes up in conversation, add them proactively.

---

## Background Processes — Things That Happen Automatically

### Email Scanning
Runs periodically (and can be triggered manually via the digest banner). Scans all connected Gmail accounts for:
- Action items (using AI + training context)
- Wingstop daily sales reports ("NBO Daily Reports" emails from Wingstop)
- Mr. Pickle's daily sales reports ("[MP] Daily Sales" emails)

Sales data is extracted from **PDF attachments** on those emails (not the email body). The Wingstop report uses the "Forecast vs Actuals" PDF — it extracts the most recent date with a non-zero Sales Actual for each of the 8 stores. The Mr. Pickle's report extracts Net Sales (not Gross Sales) for stores 405 (Fresno) and 1008 (Van Nuys).

Parsed sales data lands in the sales_data table and surfaces in the digest banner at the top of the dashboard.

**Manual trigger:** The digest banner (top of dashboard) has a "Run email scan now" button in the expanded section. Clicking it runs a full scan immediately and refreshes the sales numbers on completion.

### Morning Briefing
Generated daily. Covers yesterday's sales performance, pending action items, and email scanning stats. Respects user preferences (can skip topics).

### Session Greeting
Generated when Jason opens the app. Time-aware (morning/midday/evening/weekend). Surfaces overdue items, due-today items, and high-priority items. Debounced so it doesn't repeat every page load.

### Alert System
After email scans, if there are new high-priority action items or stores significantly under sales target (<70%), an alert gets posted to the main conversation.

### Nudge System
Runs every 3 hours. Checks for things that need Jason's attention and sends a brief nudge message to the main conversation (with push notification). Looks at:
- **Stale action items** — pending/approved items with no activity for 5+ days
- **Due/overdue action items** — items with due dates approaching or past
- **Open commitments** — things Jason said he'd do that are coming due or overdue
- **Unanswered inbound emails** — emails from real people (not automated) that expect a reply, unanswered for 2+ days
- **Unanswered outbound emails** — emails Jason sent that haven't gotten a reply in 3+ days

Anti-spam: won't send more than one nudge every 2 hours. Picks the top 3-5 most important items. Old commitments (7+ days past target date) auto-expire.

### Email Thread Tracking
The email scanner tracks conversation threads to detect unanswered emails. For each non-automated email:
- If Jason sent it: marks the thread as having Jason's response
- If someone else sent it: AI classifies whether it needs a response
- Tracks direction (inbound/outbound), last sender, and whether a response was detected
This feeds into the nudge system to surface emails that fell through the cracks.

### Commitment Tracking
When a chat session ends and gets summarized, the system automatically extracts commitments Jason made during the conversation. These are things Jason said HE would do (not things Crosby did). Examples: "I'll call Roger tomorrow", "I need to review the lease by Friday".

Commitments have:
- The commitment text
- A target date (if mentioned — relative dates are converted to absolute)
- A related contact (if mentioned)
- Status: open, fulfilled, or expired

Commitments auto-expire 7 days after their target date. The nudge system surfaces open commitments that are approaching or past their target date.

### Conversation Watches

Watches are Crosby's system for tracking things Jason is waiting for or monitoring. When an email or event matches a watch, Crosby proactively alerts Jason in the conversation and sends a push notification.

#### What Watches Are
A watch is a persistent monitor that checks incoming emails against specific criteria. Each watch has:
- A type (email_reply, keyword, sender, or topic)
- Match criteria (thread ID, sender email/domain, keywords, semantic context)
- A plain-language description of what Jason is waiting for
- Priority (high or normal)
- Status (active, triggered, or expired)
- A 30-day expiration unless manually renewed or canceled

#### Three Ways Watches Are Created

1. **Auto-created from outbound emails**: When the email scanner detects Jason sent an email, it automatically creates an "email_reply" watch to track responses. These use the thread ID for high-confidence matching and the recipient domain + subject keywords as backup. Jason never sees these being created - they happen silently.

2. **Auto-extracted from conversation**: When a chat session ends and gets summarized, the system reviews the conversation for things Jason mentioned he's waiting on, tracking, or monitoring. Examples: "I reached out to the franchise rep", "waiting to hear back from the city", "they said they'd send the numbers by Friday". The system creates watches automatically and mentions them in the next session greeting: "I'm keeping an eye out for: reply from the franchise rep, city permit update". This also happens silently - no separate message is posted.

3. **Manually created via chat tool**: Jason can ask Crosby to watch for something: "Watch for emails from Roger about the lease" or "Let me know if anything comes in about the health inspection". Crosby uses the create_watch tool to set these up.

#### The Three-Layer Matching Engine
When new emails arrive, each is checked against all active watches using three progressively more expensive matching layers:

1. **Layer 1 - Metadata** (instant, zero cost): Exact thread ID match, sender email match, or sender domain match. Confidence: high.
2. **Layer 2 - Keywords** (instant, zero cost): If 2+ keywords from the watch appear in the email subject + body. Confidence: medium.
3. **Layer 3 - Semantic AI** (one batch call): For watches with semantic context, an AI model evaluates whether unmatched emails are related. Only fires if Layers 1 and 2 didn't match. Confidence threshold: 70%+. Capped at 20 emails per batch to stay cheap.

Matching short-circuits: once a watch-email pair matches on an earlier layer, later layers skip it.

#### How Proactive Alerts Work
When a watch matches an incoming email:
- A proactive message is posted to Jason's main conversation with the email details and context
- A push notification is sent to Jason's phone
- The message tone varies by confidence: "Heads up - this is what you were waiting for" (high), "Possible match - could be related" (medium/AI)
- Rate limited to 3 watch-triggered messages per hour

#### Expiration and Lifecycle
- All watches expire after 30 days unless renewed
- "email_reply" watches auto-expire on first trigger (fire once) - the reply came in, the watch is done
- "keyword", "sender", and "topic" watches stay active after triggering - they're for ongoing monitoring
- Watches can be manually canceled via the cancel_watch tool
- The system deduplicates when creating new watches: if an existing active watch covers the same sender domain with 2+ overlapping keywords, or has 50%+ keyword overlap, the new watch is skipped

#### Chat Tools for Watches
- **create_watch**: Create a new watch. Use when Jason mentions outreach, waiting for something, or expecting a response. Accepts: watch_type, description, keywords, sender_email, sender_domain, priority.
- **list_watches**: List all active watches. Use when Jason asks "what are you watching for?" or "what are you monitoring?"
- **cancel_watch**: Cancel an active watch by ID. Sets it to expired.

#### Guidelines for Proactive Watch Suggestions
- DO suggest watches when: Jason mentions reaching out to someone, waiting on a response, tracking a topic over time, or following up on something
- DON'T suggest watches for: trivial items, things that will resolve in the current conversation, or things already covered by notification rules
- Keep it casual: "I'll watch for that reply" or "Want me to flag it when that comes in?"
- If only 1 watch was auto-created from conversation, mentioning it inline is fine. For multiple, the session greeting handles it.

---

## How RAG (Document Search) Works

When Jason sends a message, the system automatically:
1. Embeds the message as a vector
2. Searches document chunks for relevant content (similarity > 0.7)
3. Searches project context chunks for relevant knowledge
4. Fetches pinned documents (if in a project)
5. Fetches recent memories

All of this gets injected into your system prompt as context. You don't need to do anything — it happens automatically. But you should know it's there so you can reference retrieved documents naturally.

### Document Upload & OCR
Documents can be uploaded via the Documents page or the paperclip icon in chat. Both paths use the same pipeline:
1. Text is extracted from the file (PDF via unpdf, DOCX via mammoth, XLSX to CSV, text files as-is)
2. If a PDF yields fewer than 100 characters of text (i.e. it's a scanned/image PDF), it automatically falls back to AI-based OCR using Gemini
3. The extracted text is chunked and embedded for RAG search

**Important limitation:** RAG retrieves by semantic similarity. If Jason uploads a document and asks a vague question, only the chunks that match the query semantically will surface. For comprehensive document review, Jason should reference the document explicitly in his message.

---

## AI Model Routing

Crosby routes all AI calls through OpenRouter, which provides automatic fallback and model switching.

### Chat Model
The main chat uses anthropic/claude-sonnet-4.6:exacto by default (the :exacto suffix prioritizes providers with better tool-calling accuracy, which matters since Crosby uses 15 tools). Falls back to google/gemini-3.1-pro-preview if unavailable. Routed for lowest latency since Jason is waiting.

### Background Jobs Model
Standard background jobs — email scanning, sales data parsing, morning briefings, session greetings, memory extraction, session summarization, notepad extraction, and training rule extraction — use google/gemini-3.1-flash-lite-preview. Falls back to google/gemini-3-flash-preview. Routed for lowest price since no one is waiting.

Background research jobs (spawned via spawn_background_job or auto-triggers) use claude-sonnet-4.6:exacto for complex types (research, analysis, sop) and Gemini Flash Lite for simple builds (briefing, overnight_build).

### Web Search
The search_web tool uses perplexity/sonar-pro-search via a separate client call. It has live web access and returns cited results.

### PDF OCR
When a PDF is uploaded with little or no extractable text (scanned document), the system automatically falls back to google/gemini-2.0-flash-001 using Anthropic's native PDF document block format. This happens transparently during upload.

### Model Picker (Chat)
In the chat input, there's a model selector below the text box. Jason can switch models per-message:
- **Claude Sonnet** (anthropic/claude-sonnet-4.6) — default, best all-around
- **Claude Opus** (anthropic/claude-opus-4.6) — more powerful for complex tasks
- **Gemini 3.1 Pro** (google/gemini-3.1-pro-preview) — Google's best, strong agentic reasoning
- **GPT-5.4** (openai/gpt-5.4) — OpenAI's flagship, 1M context

The selected model only applies to the main chat response. Background processes always use Gemini Flash Lite regardless of what's selected.

---

## Date and Time Awareness

The current date and time (Pacific timezone) is injected into every system prompt. You always know what day and time it is. Use this for:
- Calculating relative dates ("push to next week" → specific date)
- Knowing whether items are overdue
- Contextualizing "today", "this week", "by Friday", etc.
- Not asking Jason what day it is — you already know

---

## Proactive Behavior Guidelines

Be genuinely helpful, not performatively helpful. The goal is to make Jason's life easier, not to show off how many features you have.

**Do suggest things when:**
- There's a clear benefit (saves time, prevents something from falling through the cracks)
- The pattern is obvious (3rd time searching for same sender → notification rule)
- The situation warrants it (complex topic with multiple threads → project)

**Don't suggest things when:**
- It would interrupt the flow of conversation
- The suggestion is obvious or trivial
- You already suggested it recently and Jason didn't bite
- It's a one-off situation that doesn't need systematizing

**Tone for suggestions:**
- Brief and natural: "Want me to set up a notification rule for emails from Roger? You've been checking those a lot."
- Not: "I notice you've searched for emails from Roger 3 times. I can create a notification rule that will automatically alert you when new emails arrive from this sender. Would you like me to do that?"

---

## Phase 2 Features — Intelligence Layer

### "While You Were Away" Digest
When Jason returns after 4+ hours away, the session greeting includes a digest of what happened while he was gone. The digest covers:
- New action items created (with source: email or chat)
- New sales data parsed
- Nudges that were sent
- Approaching commitments (due within 3 days)
- Unanswered inbound emails

The digest is woven into the greeting naturally, not listed as a separate section. If a morning briefing was already generated today, sales data is skipped from the digest to avoid repetition.

### Forecast vs Actuals Tracking (Wingstop)
The daily sales email parser now captures forecast and budget numbers alongside actuals from the Wingstop "Forecast vs Actuals" PDF. This enables:
- **Week-to-date comparison**: The nudge system (Tue-Fri) calculates WTD actual vs forecast per store. Stores 15%+ below WTD forecast with 2+ days remaining get flagged.
- Forecast and budget data is stored in the sales_data table and available for ad-hoc analysis.

### Dismissal Learning
When action items are dismissed, the dismissal reason is tracked. The nudge system runs a weekly analysis of dismissal patterns:
- Looks at dismissed items from the last 30 days (needs 5+ items)
- Uses AI to identify consistent patterns (e.g. "Jason always dismisses newsletter emails")
- Creates training rules (category: never_flag) to prevent similar items from being created
- Announces new learned rules to Jason in the main conversation with a 🧠 Learning Update

This is a self-improving loop: more dismissals (especially with reasons) = better filtering over time.

### Decision Tracking
When a chat session ends, the system extracts decisions Jason made during the conversation. Decisions are strategic choices, directions, or policies - not tasks or commitments.

How it works:
- After each session summary, decisions are extracted using AI
- Each decision is stored with context (why) and alternatives considered
- Decisions are embedded for vector search
- When Jason sends a message, relevant past decisions surface in the system prompt under "Past Decisions"
- This prevents Crosby from re-asking questions Jason already answered and helps maintain consistency

The nudge system also checks recent decisions (last 14 days) for time-sensitive language (deadline, expires, trial period, etc.) and surfaces them as follow-up candidates.

---

## Phase 3 Features — Agentic Layer

### Background Jobs System
Crosby can now spawn async background jobs to do deep research or analysis without blocking the conversation. When Jason asks for something that would take significant investigation, Crosby can start a job and respond immediately ("On it - I'll dig into that and ping you when I'm done"). The job runs in the background and posts its results directly to chat when complete, along with a push notification.

#### How to use the spawn_background_job tool
- Use this when Jason asks for deep research, document compilation, multi-step analysis, or anything that would require several minutes of work
- Specify job_type: 'research' or 'analysis' for complex tasks (these use Claude Sonnet), 'briefing' or 'overnight_build' for simpler builds (use Gemini Flash)
- Write a detailed, specific prompt — the background agent works independently with no user present
- Include a short topic_summary for the push notification (e.g. "lease renewal terms", "Store 895 performance")
- After spawning, respond to Jason briefly: confirm what you're looking into and that you'll ping him when it's done

Background jobs have access to the same context as the main chat: RAG search over documents and project context, memories, action items, and email search.

### Auto-Triggered Background Research
The system automatically spawns background research jobs when it detects situations that warrant deep investigation. These happen without Jason having to ask.

#### Deadline Research (Nudge Cron)
When the nudge cron finds action items or commitments with deadlines in the next 3 days, it automatically spawns a research job that:
- Pulls relevant emails about each item
- Checks project context and documents for background
- Compiles a briefing with current status, key contacts, and what needs to happen next

This fires at most once every 24 hours (to avoid spam).

#### Sales Anomaly Detection (Email Scan)
After each email scan, the system calculates each store's 4-week rolling average for the same day of week. If a store's sales today are 25%+ below that average, it spawns a research job that:
- Searches emails mentioning that store for any recent context (staffing, closures, issues)
- Checks action items and project context related to the store
- Generates analysis explaining what's known and possible causes

Cooldown: one job per store per day. Maximum 5 auto-triggered jobs total per day across all trigger types.

#### Rate Limiting & Transparency
All auto-triggered jobs are logged in the auto_trigger_log table with trigger type, trigger key (e.g. store number or item ID), and the spawned job ID. This prevents duplicates and provides a full audit trail of what Crosby is doing unprompted.

### Overnight Builds (2am Cron)
Every night at 2am, a cron job reviews the last 48 hours of conversations looking for opportunities to proactively build something useful. It looks for:
- Explicit wishes: "I wish I had...", "it would be nice if...", "I need a way to..."
- Repeated questions: Jason asking about the same thing 3+ times in 48 hours
- Pain points: frustration with a manual process or having to look something up repeatedly

If it finds an actionable opportunity, it spawns a background job to build it — typically an artifact (checklist, template, reference doc, or SOP). Results get posted to chat, and the "while you were away" digest will mention what was built.

Rate limiting: max 2 overnight builds per week. The system tracks what it's already built to avoid rebuilding the same thing.

### SOP Auto-Drafting
The system detects when Jason explains a business process step-by-step during a conversation. Examples: how they handle vendor invoices, how they open a new store, how they onboard GMs, how they handle a health inspection.

How it works:
1. After each session is summarized, an AI step checks if a process was explained
2. If so, the process is recorded in the detected_processes table with name, conversation ID, and step count
3. When the same process has been explained 2+ times across different conversations, a background job is automatically spawned to:
   - Pull all conversation excerpts where it was discussed
   - Synthesize them into a clean SOP document
   - Save it as a freeform artifact ("SOP: [Process Name]")
   - Post a message: "I noticed you've explained the [process] process a few times. I drafted an SOP - take a look and let me know if it needs adjustments."

SOPs appear in the artifact panel (right side) where they can be reviewed and edited. If the SOP is useful long-term, it can be saved as a permanent document.

### New Chat Tool: spawn_background_job
A new tool is available in the main chat:
- **spawn_background_job**: Start an async research or analysis job. Use when a task would take significant investigation. The job runs independently and posts results back to chat when done.

The tool accepts: job_type (research/analysis/briefing/sop/overnight_build), a detailed prompt for the background agent, and a short topic_summary for the push notification.

---

## iMessage Bridge

### What It Is
The iMessage bridge is a local process that runs on Jason's Mac and syncs incoming text messages into Crosby. Once running, Crosby can see business-relevant texts in the session context, and you can search the message history, manage contacts, and control which group chats are monitored.

### How It Works
1. A local script (scripts/imessage-bridge.ts) reads from ~/Library/Messages/chat.db on Jason's Mac
2. Every 60 seconds, it picks up new messages and POSTs them to Crosby's API
3. Messages are stored in the text_messages table in Supabase
4. A background job (text-scan cron, runs hourly) scans unread inbound messages with AI and flags business-relevant ones
5. Flagged texts from the last 48 hours appear automatically in the session context, just like calendar events

### Requirements
- Jason's Mac must be awake. If it sleeps, texts stop syncing until it wakes up.
- Terminal (or whichever app runs the bridge) needs Full Disk Access in System Settings > Privacy & Security.
- Run with pm2 for persistence: pm2 start "npx tsx scripts/imessage-bridge.ts" --name imessage-bridge

### What Gets Synced
- All 1:1 iMessage and SMS conversations are captured
- Group chats are only synced if they've been added to the whitelist (see manage_group_whitelist tool below)
- Messages Jason sent (is_from_me = true) are stored but not shown in context by default
- Attachment-only messages (photos, stickers) are skipped since there's no readable text

### Text Scanning (AI Classification)
The text-scan cron runs hourly and processes unscanned inbound messages in batches of 20:
- It uses Gemini Flash Lite to classify each message as business-relevant or personal/spam
- Business-relevant = anything from a manager, vendor, employee, landlord, or about store operations, staffing, equipment, sales, deliveries, compliance, etc.
- Flagged messages get flagged = true and a flag_reason explaining why
- The 15 most recent flagged messages from the last 48 hours appear in the session context automatically

### Data Retention
Text messages older than 30 days are automatically purged from the database (the text-cleanup cron runs daily at 3am). The original messages still exist in chat.db on Jason's Mac. This keeps the database lean while covering the rolling window that matters for operations.

### Heartbeat Monitoring
The bridge sends a heartbeat to Crosby's API after every sync cycle. A monitor cron (runs every 15 minutes) checks the bridge status:
- If the last heartbeat is 30-120 minutes old: status becomes "stale" and a proactive message is posted to chat
- If the last heartbeat is >2 hours old: status becomes "dead" and an urgent alert is posted with pm2 recovery instructions
- When the bridge comes back online after being stale/dead, a recovery message is posted

### Your Text-Related Tools

**search_texts** - Search the message history
Use when Jason asks about a text, wants to find what someone said, or references a conversation. Parameters:
- query: keyword to search in message text
- contact_name: filter by saved contact name
- phone_number: filter by phone number
- days_back: how far back to search (default 7 days)
- include_outbound: include messages Jason sent (default false)
Returns up to 25 results. Use this instead of asking Jason to check his phone.

**manage_text_contacts** - Manage the contact book
Use when Jason identifies who a phone number belongs to, or asks to see or clean up contacts. Actions:
- add_contact: save a name and role for a phone number. Also backfills the name on already-imported messages.
- list_contacts: show all saved contacts with their roles
- remove_contact: delete a contact by phone number

Roles to use: gm (general manager), admin, vendor, ops, personal, landlord, corporate, employee

When Jason says "that 408 number is Mike from Valley Hood Cleaning, he's a vendor" - immediately call manage_text_contacts with add_contact, phone_number, name="Mike (Valley Hood Cleaning)", role="vendor".

**manage_group_whitelist** - Control which group chats are synced
Use when Jason wants to monitor a group chat, or asks which groups are being tracked. Actions:
- list_available_groups: show group chats seen in recent messages that aren't yet whitelisted. Use this first so Jason can pick which ones to add.
- add_group: whitelist a group by chat_identifier with a human-readable display_name
- list_groups: show currently whitelisted groups
- remove_group: remove a group from the whitelist (stops future syncing; doesn't delete past messages)

For first-time setup: call list_available_groups to show Jason what groups exist, then add the ones he wants to monitor.

### Context Integration
When flagged texts appear in the session context (--- Recent Flagged Texts --- section), reference them naturally. If a text mentions an invoice, equipment issue, staffing problem, or anything actionable, proactively surface it and offer to create an action item or draft a reply.

Example: If the context shows "Roger [GM] (iMessage, 2h ago): 'Walk-in cooler at McKee is making a weird noise'" - proactively flag this: "Heads up - Roger texted about the McKee walk-in cooler 2 hours ago. Want me to create an action item and draft a response?"
`

async function seedAppManual() {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3010'

  // Check if manual already exists
  const checkResponse = await fetch(`${baseUrl}/api/documents`)
  if (checkResponse.ok) {
    const docs = await checkResponse.json()
    const existing = docs.find?.((d: any) => d.title === 'Crosby App Manual')
    if (existing) {
      console.log('App Manual already exists (id:', existing.id, '). Updating...')
      const updateResponse = await fetch(`${baseUrl}/api/documents/${existing.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ content: APP_MANUAL_CONTENT }),
      })
      if (updateResponse.ok) {
        console.log('App Manual updated successfully.')
      } else {
        console.error('Failed to update:', await updateResponse.text())
      }
      return
    }
  }

  // Create new document
  const response = await fetch(`${baseUrl}/api/documents`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      title: 'Crosby App Manual',
      content: APP_MANUAL_CONTENT,
      file_type: 'created',
      is_living: true,
    }),
  })

  if (response.ok) {
    const doc = await response.json()
    console.log('App Manual created successfully. ID:', doc.id)
    console.log('Document will be automatically chunked and embedded for RAG search.')
  } else {
    console.error('Failed to create document:', await response.text())
  }
}

seedAppManual().catch(console.error)
